### ISSUE TITLE
一些特殊符号的支持不好，多余空格并无删除

### ISSUE THREAD

**Issue by chenqiangzhishen** [hotoo/pangu.vim#10]
使用  `.` 的支持不行。

比如：
“将 Pangu.vim 添加到.vimrc  中”， 并没有在 .vimrc 前后自动添加空格。

还有就是有多个空格时，并没有将多余的空格删除。

**Comment by hotoo** [comment]
这个工具并不能完美解决所有的问题，我计划是写 [另外一个工具](https://github.com/hotoo/pangu) ，这个工具不准备做更多的支持了。如果你有兴趣，可以自己提交 PR 来解决你的问题。
