### ISSUE TITLE
在简体中文中，在一些情况下允许叠用叹号不超过三次

### ISSUE THREAD

**Issue by jiacj** [hotoo/pangu.vim#11]
在 2011 年 12 月 31 日发布的《标点符号用法》中有以下规定：“4.3.3.3 表示声音巨大或声音不断加大时，可叠用叹号；表达强烈语气时，也可叠用叹号，最多叠用三个叹号。在没有异常强烈的情感表达需要时不宜叠用叹号。”

**Comment by hotoo** [comment]
那还是不处理用户输入的重复标点符号好了。

感谢。

- [标点符号用法 GB/T 15834 2011](http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf)

**Comment by jiacj** [comment]
可是只有叹号允许叠用，其他的不行……

**Comment by hotoo** [comment]
好了，根据《标点符号用法》，感叹号、问号最多可以连续 3 个，其他的只允许使用一个。
