### ISSUE TITLE
Error occur when exectuing `:argdo Pangu | update`

### ISSUE THREAD

**Issue by XiaochenCui** [hotoo/pangu.vim#12]
```
"404.md" [最后一行不完整] 6 行，81 characters
E488: 多余的尾部字符: Pangu | update
"_drafts/CheetahDB-轻型数据库.md" [最后一行不完整] 15 行，487 characters
E488: 多余的尾部字符: Pangu | update
```

**Comment by hotoo** [comment]
argdo 命令确实可以带 `|` 传入多个命令，但是实际上并没有将命令拆开，导致实际执行了 `Pangu | update` 命令，后面的 `| update` 被 Pangu 当作参数了，于是抛出了这个异常。

默认情况下自定义命令都是不允许带参数的，而且 `Pangu` 确实也不需要参数。`:h :command-nargs`

要解决这个问题可以改 `-nargs=*`，但是我觉得这是 argdo 的问题。

**Comment by hotoo** [comment]
请重新安装。
