### ISSUE TITLE
使用 `%s/*/*/gg` 替换 `%s/*/*/g`

### ISSUE THREAD

**Issue by KnightPublic** [hotoo/pangu.vim#13]
在 Vim 中 `%s/*/*/gg` 可以替换一行中的多处匹配，而 `%s/*/*/g` 只能替换一行中的第一处匹配。

**Comment by hotoo** [comment]
欢迎 MR

**Comment by KnightPublic** [comment]
很抱歉，我的 `vimrc` 中添加了 `set gdefault` 执行使用 `s///g` 时，相当于执行 `s///gg`，执行 `s///gg` 时相当于执行 `s///ggg` （两个 `g` 相当于没有使用 `g`），所以如果没有 `set gdefault` 时，`s///g` 可以替换一行中的所有匹配。希望以上信息可以帮助关闭该 issue。
