### ISSUE TITLE
格式化文本的时候卡顿明显

### ISSUE THREAD

**Issue by ganziqim** [hotoo/pangu.vim#17]
使用盘古插件进行格式化的时候有明显卡顿，遇到稍微大点的问题（其实也没多大，几百行上千行的那种）跑格式化的时候会卡住很长时间，如果在格式化期间进行别的操作则会强制退出，不知道是不是受到别的插件或者 vim 版本的影响？（下附）

不知道格式化是否能使用最新的异步接口？如果可以的话应该使用起来的感受会好一些。（之前使用 sytastic 很卡，切换到 ale 之后卡顿就消失了）

作者大大如果需要别的额外信息请联系我，我尽量提供完整的信息。最近在学习 vimscript，也可以帮忙写一些小功能...

macOS 版本：10.13.4
neovim 版本：v0.2.2
iTerm2 版本：3.1.6

**Comment by hotoo** [comment]
@ganziqim 请提供一份目标文本给我看看
