### ISSUE TITLE
某些情况下格式化括号时有一侧没有正确格式化

### ISSUE THREAD

**Issue by shidenggui** [hotoo/pangu.vim#18]
如下情况 

```
测(测 test) ， 测
```

期望执行之后，两侧都被格式化为中文括号，实际只有左侧被正确格式化

```
测（测 test） ， 测
```

只有在如下情况时，两侧才能正确格式化为中文括号

```
测(测 test 测)测 ， 测
```

**Comment by hotoo** [comment]
这个难度比较大，而且还需要考虑到括号嵌套的情况。
如果你有什么好的方案，欢迎探讨和 PR
