### ISSUE TITLE
建议取消对反斜杠\及括号[]的转化处理

### ISSUE THREAD

**Issue by ChenWeird** [hotoo/pangu.vim#26]
> 总之，Markdown 的语法全由一些符号所组成，这些符号经过精挑细选，其作用一目了然。比如：在文字两旁加上星号，看起来就` \*强调\*`。Markdown 的列表看起来，嗯，就是列表。Markdown 的区块引用看起来就真的像是引用一段文字，就像你曾在电子邮件中见过的那样。

上述的`\*强调\*`会被不正确的转义为`、*强调、*`

**Comment by ChenWeird** [comment]
建议取消将`[]`转为中文`『』`，否则对很多包含代码的相关文档协作非常不方便。

**Comment by hotoo** [comment]
绝大部分情况都不是介绍 Markdown 这种场景。如果你是这种场景，可以 `PANGU_DISABLE` 持久化关闭 pangu 规范化。

**Comment by sudoyang** [comment]
Latex中也遇到类似问题比如\cite{}会被转为、cite{}。
