### ISSUE TITLE
考虑基于语法的精确规范化工具

### ISSUE THREAD

**Issue by hotoo** [hotoo/pangu.vim#4]
我在想怎么做一个基于语法的规范化工具，针对不同的文件格式，先分析 AST，然后针对需要替换的部分进行规范化。但是目前很多 AST 工具会破坏原始文件的一些细节，比如空白、空行等，最终输出替换后的结果可能会激怒用户。而且整个文档替换也有一些副作用。

没想清楚。

**Comment by Firef0x** [comment]
@hotoo ，您好！

哇，很高兴 `Pangu.vim` 插件终于从词法分析阶段上升到文法分析阶段 :scream: ，一直觉得对自然语言进行文法分析是一项很高端的技术。我刚好想提两个建议：

1. 考虑和 [scrooloose/syntastic](https://github.com/scrooloose/syntastic) [#2736](http://www.vim.org/scripts/script.php?script_id=2736) 的集成兼容。
    由于目前会存在纠正过度的情况，因而最好能够提供只检查不纠正的功能。在这方面我觉得 Syntastic 做得还是比较好的，既可以添加 `:sign` ，也可以输出到 QuickFix 出错窗口。

2. 考虑增加类似 [vim-vimlint/vimlint.sh](https://github.com/syngan/vim-vimlint/blob/master/bin/vimlint.sh) 这样的 Shell 脚本。既然能够提供只检查不纠正的功能，那么把它做成只通过执行一个脚本就可以输出所有问题就更方便了。这样做的方便之处是可以集成到 Travis-CI 等持续集成系统，对每一次提交以及拉取请求进行自动检查。

当然这两个建议都属于“特性增强”类别的，目前优先级最高的应该是解决纠正过度的问题。

此致！ :bow:

**Comment by hotoo** [comment]
嗯，syntastic 这个我考虑过的。
同时欢迎你提交 PR ：）

**Comment by hotoo** [comment]
不在这个 VimScript 插件中实现。
