### ISSUE TITLE
无法修复 markdown 链接所使用的标点

### ISSUE THREAD

**Issue by kkew3** [hotoo/pangu.vim#49]
例子输入：

```
【例子】（./example.md)
```

期望输出：

```
[例子](./example.md)
```

实际输出：

```
〖例子〗（./example.md)
```

怀疑和 commit 277bb4347de9e4fc9489d78c4361692a6fdaa5dd “fix: chinese bracket (【】) in markdown links” 有关。

---

BTW commit 277bb4347de9e4fc9489d78c4361692a6fdaa5dd 将 `[【内容】内容](https://www.example.com/)` 替换成了 `[〖内容〗内容](https://www.example.com/)`，修改了原括号样式，不知是否有更好的解决方法？

**Comment by hotoo** [comment]
这样会导致用户无法正常输入中文中括号后面直接用中文圆括号。
抱歉，不考虑这样的支持。
