### ISSUE TITLE
Markdown Links 首个字符是中括号〖

### ISSUE THREAD

**Issue by kkew3** [hotoo/pangu.vim#50]
当令变量 `let g:pangu_punctuation_brackets = ["〖", "〗"]` 时，

例子输入：

```
[〖内容〗内容](https://www.example.com/)
```

期望输出：不变

实际输出：

```
〖内容〗内容〗(https://www.example.com/)
```

谢谢

**Comment by hotoo** [comment]
先使用默认的方括号吧，〖 被用做了兜底方案，目前没想好这个怎么处理。

**Comment by hotoo** [comment]
fixed, 请使用最新的版本。
