### ISSUE TITLE
同一行中文中出现多个英文句点，只能替换最后面的一个吗？

### ISSUE THREAD

**Issue by tankb52** [hotoo/pangu.vim#57]
示例：说完第一句，这是第一个句号.再说第二句，这是第二个句号.这是第三个句号.
执行命令 :Pangu
预期：说完第一句，这是第一个句号。再说第二句，这是第二个句号。这是第三个句号。
结果：说完第一句，这是第一个句号.再说第二句，这是第二个句号.这是第三个句号。

这是规范如此还是 Pangu 插件替换出错了呢？

**Comment by hotoo** [comment]
@tankb52 这是特意设计的，为了避免 `啊...` 被替换成 `啊。..`
如果英文点号后面有空白，或者在行尾，是可以正常替换的。

**Comment by tankb52** [comment]
> @tankb52 这是特意设计的，为了避免 `啊...` 被替换成 `啊。..` 如果英文点号后面有空白，或者在行尾，是可以正常替换的。

原来这样，那我理解了。
