### ISSUE TITLE
提供 options 設定排版規則

### ISSUE THREAD

**Issue by bootleq** [hotoo/pangu.vim#7]
印象中「盤古之白」最有名的功能是「偏執地在中英文之間加上空白」，而 pangu.vim 好像志在更完整的中文排版規範，提供了不少額外規則；先不論哪些規則是 pangu.vim 該做的，是否可以有 options 能自訂排版行為？除了能滿足不同情境的使用者，也能減少釋出新版時，行為變更帶來的衝擊。

我擬了一些 option 名稱，會再試著發 pr 上來～
https://github.com/bootleq/pangu.vim/blob/options/doc/pangu.txt#L15

**Comment by hotoo** [comment]
嗯，这个插件最初也是为了在中英文之间增加空白的功能，后来逐渐的完善了更多的中文规范化特性，发展成了现在的样子。

但是『盘古之白』是非常具有典型意义和重要的一个概念，所以插件还是保留了这个简单直白的名称。

关于选项问题，我之前也想过，后来经过一些实践，现在提供的默认规范化方案是最优方案，可选的并不多，意义不大，所以也就没有做。

不过你可以尝试做些选项看看。
