### ISSUE TITLE
支持 Range 操作

### ISSUE THREAD

**Issue by psjay** [hotoo/pangu.vim#8]
有的时候不想要格式化整个文档，只需要格式化其中的某一部分。

**Comment by district10** [comment]
我属于不喜欢给 Vim 装插件的那种，但我发现 pangu.vim 很有用。其实你可以这么用，把

```
silent! '<,'>s/\([\u4e00-\u9fa5\u3040-\u30FF]\)\([a-zA-Z0-9@&=\[\$\%\^\-\+(\/\\]\)/\1 \2/g
silent! '<,'>s/\([a-zA-Z0-9!&;=\]\,\.\:\?\$\%\^\-\+\)\/\\]\)\([\u4e00-\u9fa5\u3040-\u30FF]\)/\1 \2/g
```

拷贝到剪切板（就是 vim 的 `+` 寄存器，可以用 `"+p` 确认一下拷贝成功了）。
然后在 Visual Mode 选定文字，执行 `:@+`。就可以把选定内中英间加上空格了。

Hope this help.
